name: Publish to PyPI

on: [push, pull_request]

#on:
#  release:
#    types: [created]
#    branches:
#      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    environment: release
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Need this to get version number from last tag
          fetch-depth: 0

      - name: Build sdist and wheel
        run: >
          export SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct) &&
          pipx run build

      - name: Check for packaging errors
        run: pipx run twine check --strict dist/*

      - name: Install produced wheel
        run: pip install dist/*.whl

      - name: Test module is importable using the installed wheel - 1
        run: python -c "import save_and_restore_api"

      - name: Test module is importable using the installed wheel - 2
        run: python -c "from save_and_restore_api import SaveRestoreAPI"

      - name: Test module is importable using the installed wheel - 3
        run: python -c "from save_and_restore_api.aio import SaveRestoreAPI"

      - name: Test if save-and-restore tools can be started
        run: save-and-restore -h


      #- name: Publish to PyPI using trusted publishing
      #  uses: pypa/gh-action-pypi-publish@release/v1
      #  with:
      #    attestations: false
